management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
#    shutdown:
#      enabled: true
    health:
      show-components: always
#       show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
info:
  app:
    name: hello-actuator
    company: bj

logging:
  level:
    hello.controller: debug



#  endpoint:
#    shutdown:
#      enabled: true