management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
#      show-details: always
#  endpoint:
#    shutdown:
#      enabled: true